### ISSUE TITLE
Change the wording used on facet filters

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/search#22]
People seem confused by the words we're using on the facet filter options.

Change “Index” and “Type” labels

- Change “Index” to “Filter By”
- Change “Website” to “Website Content”
- Change “Boards & Commissions” to “Board Agendas, Minutes, & Packets” 
- Change “Type” to “Filter by Type”

**Comment by inghamn** [comment]
"Boards Agenda, Minutes, & Packets" is really long and wraps.  Is this a problem

![screen](https://user-images.githubusercontent.com/630282/145876637-b495f911-6bf9-4b5b-9a70-6b4df1737c38.png)
?

**Comment by adabutch** [comment]
Update to the long text problem above.

My commit had a pound typo, so here is the ref to it 😅 

https://github.com/City-of-Bloomington/search/commit/e62598b5eeb6926898e287faebb1e7f08b2910c5
